version: '3'

services:
  sistema:
    build: ./app
    container_name: sistema_app
    ports:
      - "5000:5000"
    depends_on:
      - bd
    networks:
      - app-network

  bd:
    image: mysql:5.7
    container_name: mysql_bd
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
